apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: apo4nr9hc-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/apo4nr9hc-dotnet-basic-gitops